INSERT INTO `tVendor`(`name`) VALUES ("yahoo");
INSERT INTO `tVendor`(`name`) VALUES ("hkex");
INSERT INTO `tVendor`(`name`) VALUES ("hkma");

INSERT INTO `tSymbol` (`symbol`, `preferredVendor`, `availVendors`, `currency`, `name`) VALUES
('0001.HK', 'yahoo', 'yahoo', 'HKD', 'CKH Holdings'),
('0002.HK', 'yahoo', 'yahoo', 'HKD', 'CLP Holdings'),
('0003.HK', 'yahoo', 'yahoo', 'HKD', 'HK & China Gas'),
('0004.HK', 'yahoo', 'yahoo', 'HKD', 'Wharf Holdings'),
('0005.HK', 'yahoo', 'yahoo', 'HKD', 'HSBC Holdings'),
('0006.HK', 'yahoo', 'yahoo', 'HKD', 'Power Assets'),
('0011.HK', 'yahoo', 'yahoo', 'HKD', 'Hang Seng Bank'),
('0012.HK', 'yahoo', 'yahoo', 'HKD', 'Henderson Land'),
('0016.HK', 'yahoo', 'yahoo', 'HKD', 'SHK Ppt'),
('0017.HK', 'yahoo', 'yahoo', 'HKD', 'New World Dev'),
('0019.HK', 'yahoo', 'yahoo', 'HKD', 'Swire Pacific A'),
('0023.HK', 'yahoo', 'yahoo', 'HKD', 'Bank of E Asia'),
('0027.HK', 'yahoo', 'yahoo', 'HKD', 'Galaxy Ent'),
('0066.HK', 'yahoo', 'yahoo', 'HKD', 'MTR Corporation'),
('0083.HK', 'yahoo', 'yahoo', 'HKD', 'Sino Land'),
('0087.HK', 'yahoo', 'yahoo', 'HKD', 'Swire Pacific B'),
('0101.HK', 'yahoo', 'yahoo', 'HKD', 'Hang Lung Ppt'),
('0144.HK', 'yahoo', 'yahoo', 'HKD', 'China Mer Port'),
('0151.HK', 'yahoo', 'yahoo', 'HKD', 'Want Want China'),
('0175.HK', 'yahoo', 'yahoo', 'HKD', 'Geely Auto'),
('0267.HK', 'yahoo', 'yahoo', 'HKD', 'CITIC'),
('0288.HK', 'yahoo', 'yahoo', 'HKD', 'WH Group'),
('0386.HK', 'yahoo', 'yahoo', 'HKD', 'Sinopec Corp'),
('0388.HK', 'yahoo', 'yahoo', 'HKD', 'HKEx'),
('0390.HK', 'yahoo', 'yahoo', 'HKD', 'China Railway'),
('0489.HK', 'yahoo', 'yahoo', 'HKD', 'Dongfeng Group'),
('0688.HK', 'yahoo', 'yahoo', 'HKD', 'China Overseas'),
('0700.HK', 'yahoo', 'yahoo', 'HKD', 'Tencent'),
('0728.HK', 'yahoo', 'yahoo', 'HKD', 'China Telecom'),
('0753.HK', 'yahoo', 'yahoo', 'HKD', 'Air China'),
('0762.HK', 'yahoo', 'yahoo', 'HKD', 'China Unicom'),
('0823.HK', 'yahoo', 'yahoo', 'HKD', 'Link REIT'),
('0836.HK', 'yahoo', 'yahoo', 'HKD', 'China Res Power'),
('0857.HK', 'yahoo', 'yahoo', 'HKD', 'PetroChina'),
('0883.HK', 'yahoo', 'yahoo', 'HKD', 'CNOOC'),
('0902.HK', 'yahoo', 'yahoo', 'HKD', 'Huaneng Power'),
('0914.HK', 'yahoo', 'yahoo', 'HKD', 'Conch Cement'),
('0939.HK', 'yahoo', 'yahoo', 'HKD', 'CCB'),
('0941.HK', 'yahoo', 'yahoo', 'HKD', 'China Mobile'),
('0992.HK', 'yahoo', 'yahoo', 'HKD', 'Lenovo Group'),
('0998.HK', 'yahoo', 'yahoo', 'HKD', 'CITIC Bank'),
('1038.HK', 'yahoo', 'yahoo', 'HKD', 'CKI Holdings'),
('1044.HK', 'yahoo', 'yahoo', 'HKD', 'Hengan Int\'l'),
('1088.HK', 'yahoo', 'yahoo', 'HKD', 'China Shenhua'),
('1099.HK', 'yahoo', 'yahoo', 'HKD', 'Sinopharm'),
('1109.HK', 'yahoo', 'yahoo', 'HKD', 'China Res Land'),
('1113.HK', 'yahoo', 'yahoo', 'HKD', 'CK Asset'),
('1186.HK', 'yahoo', 'yahoo', 'HKD', 'China Rail Cons'),
('1211.HK', 'yahoo', 'yahoo', 'HKD', 'BYD Company'),
('1288.HK', 'yahoo', 'yahoo', 'HKD', 'ABC'),
('1299.HK', 'yahoo', 'yahoo', 'HKD', 'AIA'),
('1336.HK', 'yahoo', 'yahoo', 'HKD', 'NCI'),
('1339.HK', 'yahoo', 'yahoo', 'HKD', 'PICC Group'),
('1359.HK', 'yahoo', 'yahoo', 'HKD', 'China Cinda'),
('1398.HK', 'yahoo', 'yahoo', 'HKD', 'ICBC'),
('1658.HK', 'yahoo', 'yahoo', 'HKD', 'PSBC'),
('1928.HK', 'yahoo', 'yahoo', 'HKD', 'Sands China Ltd'),
('1997.HK', 'yahoo', 'yahoo', 'HKD', 'Wharf REIC'),
('2007.HK', 'yahoo', 'yahoo', 'HKD', 'Country Garden'),
('2018.HK', 'yahoo', 'yahoo', 'HKD', 'AAC Tech'),
('2318.HK', 'yahoo', 'yahoo', 'HKD', 'Ping An'),
('2319.HK', 'yahoo', 'yahoo', 'HKD', 'Mengniu Dairy'),
('2382.HK', 'yahoo', 'yahoo', 'HKD', 'Sunny Optical'),
('2388.HK', 'yahoo', 'yahoo', 'HKD', 'BOC Hong Kong'),
('2628.HK', 'yahoo', 'yahoo', 'HKD', 'China Life'),
('2800.HK', 'yahoo', 'yahoo', 'HKD', 'Tracker Fund'),
('2822.HK', 'yahoo', 'yahoo', 'HKD', 'CSOP A50 ETF'),
('2823.HK', 'yahoo', 'yahoo', 'HKD', 'ISHARES A50 ETF'),
('2828.HK', 'yahoo', 'yahoo', 'HKD', 'HS H ETF'),
('2833.HK', 'yahoo', 'yahoo', 'HKD', 'HS HSI ETF'),
('3328.HK', 'yahoo', 'yahoo', 'HKD', 'Bankcomm'),
('3988.HK', 'yahoo', 'yahoo', 'HKD', 'Bank of China'),
('8008.HK', 'yahoo', 'yahoo', 'HKD', 'Sun eVision'),
('^HSI', 'yahoo', 'yahoo', 'HKD', 'Hang Seng Index ');


